---
services:

    _defaults:
        autoconfigure: true
        autowire: true

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        public: true
        exclude:
            - '../src/Domain/Exception'
            - '../src/*/*/Value'
            - '../src/*/Value'

    PhpTuf\ComposerStager\Domain\FileSyncer\Service\FileSyncerInterface:
        factory: [ '@PhpTuf\ComposerStager\Infrastructure\FileSyncer\Factory\FileSyncerFactory', 'create' ]

    PhpTuf\ComposerStager\Infrastructure\FileSyncer\Factory\FileSyncerFactory: ~

    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Process\ExecutableFinder: ~
