---
services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        exclude:
            - '../src/Exception'

    PhpTuf\ComposerStager\Console\:
        resource: '../src/Console/*'
        public: true
        exclude:
            - '../src/Console/Output'

    PhpTuf\ComposerStager\Infrastructure\Process\FileCopier\FileCopierFactory: ~

    PhpTuf\ComposerStager\Infrastructure\Process\FileCopier\FileCopierInterface:
        factory: [ '@PhpTuf\ComposerStager\Infrastructure\Process\FileCopier\FileCopierFactory', 'create' ]

    Symfony\Component\Process\ExecutableFinder: ~

    Symfony\Component\Filesystem\Filesystem: ~
