---
services:

    _defaults:
        autoconfigure: true
        autowire: true

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        public: true
        exclude:
            - '../src/*/*/Value'
            - '../src/API/Exception'

    PhpTuf\ComposerStager\API\FileSyncer\Service\FileSyncerInterface:
        factory: [ '@PhpTuf\ComposerStager\API\FileSyncer\Factory\FileSyncerFactoryInterface', 'create' ]

    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Process\ExecutableFinder: ~
