---
services:

    _defaults:
        autoconfigure: true
        autowire: true

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        public: true
        exclude:
            - '../src/*/*/Value'
            - '../src/API/Exception'

    # It is not strictly necessary to specify these details for Composer Stager
    # itself, but they represent the way a client would configure its container.
    # Therefore it is how Composer Stager should test itself. See ../docs/README.md.
    PhpTuf\ComposerStager\Internal\FileSyncer\Factory\FileSyncerFactory:
        arguments:
            $phpFileSyncer: '@PhpTuf\ComposerStager\API\FileSyncer\Service\PhpFileSyncerInterface'
            $rsyncFileSyncer: '@PhpTuf\ComposerStager\API\FileSyncer\Service\RsyncFileSyncerInterface'
    PhpTuf\ComposerStager\API\FileSyncer\Service\FileSyncerInterface:
        factory: [ '@PhpTuf\ComposerStager\API\FileSyncer\Factory\FileSyncerFactoryInterface', 'create' ]

    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Process\ExecutableFinder: ~
