---
services:

    _defaults:
        autoconfigure: true
        autowire: true

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        public: true
        exclude:
            - '../src/Domain/Exception'
            - '../src/Infrastructure/Aggregate'
            - '../src/Infrastructure/Value'

    PhpTuf\ComposerStager\Domain\Service\FileSyncer\FileSyncerInterface:
        factory: [ 'PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\FileSyncerFactory', 'create' ]

    PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\FileSyncerFactory:
        arguments:
            $phpFileSyncer: PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\PhpFileSyncer
            $rsyncFileSyncer: PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\RsyncFileSyncer

    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Process\ExecutableFinder: ~
