---
services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        public: true
        exclude:
            - '../src/*/*/Value'
            - '../src/API/Exception'

    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Process\ExecutableFinder: ~
