---
services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        public: true
        exclude:
            - '../src/Exception'

    PhpTuf\ComposerStager\Infrastructure\FileSyncer\FileSyncerFactory:
        arguments:
            $phpFileSyncer: '@PhpTuf\ComposerStager\Infrastructure\FileSyncer\PhpFileSyncer'
            $rsyncFileSyncer: '@PhpTuf\ComposerStager\Infrastructure\FileSyncer\RsyncFileSyncer'

    PhpTuf\ComposerStager\Domain\FileSyncer\FileSyncerInterface:
        factory: [ '@PhpTuf\ComposerStager\Infrastructure\FileSyncer\FileSyncerFactory', 'create' ]

    PhpTuf\ComposerStager\Infrastructure\FileSyncer\PhpFileSyncer:
        public: true

    PhpTuf\ComposerStager\Infrastructure\FileSyncer\RsyncFileSyncer:
        public: true

    Symfony\Component\Process\ExecutableFinder: ~

    Symfony\Component\Filesystem\Filesystem: ~
