---
services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        exclude:
            - '../src/Exception'

    PhpTuf\ComposerStager\Console\:
        resource: '../src/Console/*'
        public: true
        exclude:
            - '../src/Console/Output'

    Symfony\Component\Process\ExecutableFinder:
        shared: false
