---
services:

    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $phpFileSyncer: '@PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\PhpFileSyncer'
            $rsyncFileSyncer: '@PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\RsyncFileSyncer'

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        public: true
        exclude:
            - '../src/Domain/Exception'
            - '../src/Infrastructure/Aggregate'
            - '../src/Infrastructure/Value'

    PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\FileSyncerFactory: ~

    PhpTuf\ComposerStager\Domain\Service\FileSyncer\FileSyncerInterface:
        factory: [ '@PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\FileSyncerFactory', 'create' ]

    PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\PhpFileSyncer: ~

    PhpTuf\ComposerStager\Infrastructure\Service\FileSyncer\RsyncFileSyncer: ~

    Symfony\Component\Process\ExecutableFinder: ~

    Symfony\Component\Filesystem\Filesystem: ~
