---
services:

    _defaults:
        autowire: true

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        exclude:
            - '../src/*/*/Value'
            - '../src/API/Exception'
        public: true

    Symfony\Component\Filesystem\Filesystem: ~
    Symfony\Component\Process\ExecutableFinder: ~
    Symfony\Component\Process\PhpExecutableFinder: ~
