---
services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    PhpTuf\ComposerStager\:
        public: true
        resource: '../src/*'
        exclude: '../src/Exception'

    Symfony\Component\Process\ExecutableFinder:
        shared: false
