---
services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    PhpTuf\ComposerStager\:
        resource: '../src/*'
        public: true
        exclude:
            - '../src/Console/Output'
            - '../src/Exception'

    PhpTuf\ComposerStager\Infrastructure\FileSyncer\FileSyncerFactory: ~

    PhpTuf\ComposerStager\Infrastructure\FileSyncer\FileSyncerInterface:
        factory: [ '@PhpTuf\ComposerStager\Infrastructure\FileSyncer\FileSyncerFactory', 'create' ]

    Symfony\Component\Process\ExecutableFinder: ~

    Symfony\Component\Filesystem\Filesystem: ~

    Symfony\Component\Finder\Finder: ~
