---
name: Tests

on:
  push:
    branches: [ main, wip ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  schedule:
    # Every Monday at 00:00:00 UTC.
    - cron:  '0 0 * * 1'

jobs:
  build:
    name: PHP ${{ matrix.php }} test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        php: ['7.3', '7.4', '8.0']
        experimental: [false]
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Lint PHP
        run: composer lint

      - name: Run PHPCS
        # Windows line endings wreak havoc with coding standards.
        if: matrix.operating-system != 'windows-latest'
        run: composer phpcs

      - name: Run PHPStan
        run: composer phpstan

      - name: Run PHPMD
        run: composer phpmd

      - name: Run PHPUnit
        run: composer phpunit

      - name: Check dependencies for known security vulnerabilities
        run: composer security
