---
name: Tests

on:
    push:
        branches: [ main, develop, wip ]
        paths-ignore:
            - .idea/**
            - docs/**
    pull_request:
        branches: [ develop ]
        paths-ignore:
            - .idea/**
            - docs/**
    schedule:
        # Every Monday at 00:00:00 UTC.
        # @see https://crontab.cronhub.io/
        -   cron: "0 0 * * 1"

jobs:
    quality_check:
        name: "Quality Check"
        runs-on: macos-latest
        strategy:
            fail-fast: false
        steps:
            -   name: "Set up PHP"
                uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
                with:
                    php-version: "8.1"

            -   name: "Checkout code"
                uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout

            -   name: "Install dependencies"
                uses: ramsey/composer-install@v2 # https://github.com/marketplace/actions/install-composer-dependencies
                with:
                    # Disable Composer caching due to random failures it causes.
                    # @see https://github.com/ramsey/composer-install/issues/79
                    composer-options: "--no-cache"

            -   name: "Run all quality checks"
                run: "composer static"

    tests:
        name: "Test: ${{ matrix.os }}, ${{ matrix.dependencies }} (${{ matrix.php }})"
        runs-on: "${{ matrix.os }}"
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                php: [ "8.1" ]
                dependencies: [ lowest, highest ]
        steps:
            -   name: "Debugging info"
                run: "rsync --version | head -1"
                if: ${{ runner.os != 'Windows' }}

            -   name: "Set up PHP"
                uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
                with:
                    php-version: "${{ matrix.php }}"

            -   name: "Checkout code"
                uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout

            -   name: "Install dependencies"
                uses: ramsey/composer-install@v2 # https://github.com/marketplace/actions/install-composer-dependencies
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Run core tests with coverage (Linux)"
                run: "composer test"
                if: ${{ runner.os == 'Linux' }}

            # There's no reason to generate coverage data on multiple OS-es--the result should be the same.
            -   name: "Run core tests without coverage (macOS)"
                run: "./vendor/bin/phpunit --no-coverage --exclude-group=windows_only"
                if: ${{ runner.os == 'macOS' }}

            -   name: "Run Windows tests"
                run: "./vendor/bin/phpunit --no-coverage --exclude-group=no_windows"
                if: ${{ runner.os == 'Windows' }}
