---
name: Security Check

on:
    schedule:
        # Every day at 00:00:00 UTC.
        # @see https://crontab.cronhub.io/
        -   cron: "0 0 * * *"

jobs:
    composer_audit:
        name: "Composer Audit"
        runs-on: macos-latest
        steps:
            -   name: "Set up PHP"
                uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
                with:
                    php-version: "7.4"

            -   name: "Checkout code"
                uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout

            -   name: "Install dependencies"
                uses: ramsey/composer-install@v2 # https://github.com/marketplace/actions/install-composer-dependencies
                with:
                    # Disable Composer caching due to random failures it causes.
                    # @see https://github.com/ramsey/composer-install/issues/79
                    composer-options: "--no-cache"

            -   name: "Check for security vulnerability advisories for installed packages"
                run: "composer audit"
